version: '3'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "${DOCKER_DB_PORT}:5432"
    volumes:
      - pg_otus_project:/var/lib/postgres

volumes:
  pg_otus_project: